package com.MOOC.OnlineLearningPlatfrom.Service;

import java.util.List;

public interface YouTubeService {

    record YouTubeLectureItem(
            String videoId,
            String title,
            String description,
            String videoUrl,
            String thumbnailUrl,
            int durationSeconds,
            int orderIndex
    ) {}

    record PlaylistImportResponse(
            String playlistId,
            String playlistTitle,
            String channelTitle,
            List<YouTubeLectureItem> lectures,
            int totalLectures
    ) {}

    record TranscriptResponse(
            String videoId,
            String transcriptText,
            boolean isAutoGenerated
    ) {}

    /**
     * Extracts playlist ID and imports lectures, titles, high-res thumbnails, and durations.
     */
    PlaylistImportResponse importPlaylist(String playlistUrlOrId);

    /**
     * Retrieves video transcript/captions to feed into AI Question Extractor.
     */
    TranscriptResponse getTranscript(String videoId);
}
